// Frontend/Firebase/ReactJS/src/components/RegisterForm/RegisterForm.jsx
import React, {useRef} from "react";
import './registerForm.scss';
import 'react-toastify/dist/ReactToastify.css';
import { OwnID, ownidReactService } from "@ownid/react";
import {useNavigate} from "react-router-dom";
import Header from "../Header/Header";
import {toast} from "react-toastify";
import {getAuth, createUserWithEmailAndPassword} from "firebase/auth";

function RegisterComponent() {
    const email = useRef(null);
    const password = useRef(null);
    let navigate = useNavigate();

    async function onSubmit(event) {
        event.preventDefault();
        createUserWithEmailAndPassword(getAuth(), email.current.value, password.current.value)
            .then(async () => {
                //Enroll device with OwnID
                await ownidReactService.enrollDevice();
                navigate('/login')
            })
            .catch(err => toast.error(err))
    }

    return (
        <>
            <Header/>
            <div className="nav-tabs">
                <a className="nav-link active">Register</a>
            </div>
            <form onSubmit={onSubmit} className="login-form">
                <input ref={email} type="email" name="email" placeholder="Email" required/>
                <input ref={password} type="password" name="password" placeholder="password" required/>
                <button type="submit">Register</button>
                <OwnID type='register'
                       variant='button-fingerprint'
                       infoTooltip={true}
                       loginIdField={email}
                       passwordField={password}
                       onError={(error) => console.error(error)}/>
            </form>
            <div className="custom-link" onClick={() => navigate('/login')}>
                <div className="link-text">Already have an account?</div>
            </div>
        </>
    );
}

export default RegisterComponent;

// Frontend/Firebase/Angular/src/app/components/register-form/register-form.component.ts
import { Component, OnInit } from '@angular/core';
import {createUserWithEmailAndPassword,getAuth} from 'firebase/auth';
import {Router} from "@angular/router";
import {InlineWidgetVariants, OwnidAngularService, WidgetType} from '@ownid/angular';
import {FormBuilder, FormGroup, Validators} from "@angular/forms";
@Component({
  selector: 'app-register-form',
  templateUrl: './register-form.component.html',
  styleUrls: ['./register-form.component.scss']
})
export class RegisterFormComponent implements OnInit {

  widgetOptions = { variant: InlineWidgetVariants.ButtonFingerprint, infoTooltip: true };
  register: WidgetType = WidgetType.Register;
  loginIdField: string | undefined;
  passwordField: string | undefined;
  ownIDData: string | undefined;
  userForm: FormGroup;

  constructor(private router: Router, private ownidAngularService: OwnidAngularService,formBuilder: FormBuilder) {
    this.userForm = formBuilder.group(
      {
        email: [null, [Validators.required]],
        password: [null, [Validators.required]],
      },
      { updateOn: 'change' });
  }

  ngOnInit(): void {
  }

  onRegister(ownIdData: string) {
    this.ownIDData = ownIdData;
  }

  onSubmit() {
    createUserWithEmailAndPassword(getAuth(), this.userForm.get('email')?.value, this.userForm.get('password')?.value)
      .then(async () => {
        //Enroll device with OwnID
        await this.ownidAngularService.enrollDevice();
        this.router.navigateByUrl('/login')
      })
      .catch(err => alert(err));
  }
}

<div class="nav-tabs">
  <a class="nav-link active">Register</a>
</div>
<form [formGroup]="userForm" class="registration-form" (ngSubmit)="onSubmit()">
  <input formControlName="email"  type="email" #email name="email" placeholder="Email" required/>
  <input formControlName="password" type="password" #password name="password" placeholder="password" required/>
  <button type="submit">Register</button>
  <ownid [type]="register"
         (onRegister)="onRegister($event)"
         [loginIdField]="email"
         [passwordField]="password">
  </ownid>
</form>
<div class="custom-link">
<div class="link-text" routerLink="/login">Already have an account?</div>
</div>
