// Frontend/Custom/ReactJS/src/components/LoginForm/LoginForm.jsx
import React, {useRef} from "react";
import './loginForm.scss';
import {OwnID} from "@ownid/react";
import {useNavigate} from "react-router-dom";
import Header from "../Header/Header";
import {loginUser} from "../../services/httpRequests";
import {toast} from "react-toastify";


function LoginForm() {
    const email = useRef(null);
    const password = useRef(null);
    let navigate = useNavigate();

    function onSubmit(event) {
        event.preventDefault();
        //Call your existing registration logic in the backend
        return login({loginId: email.current.value, password: password.current.value});
    }

    function login(userData) {
        loginUser(userData)
            .then(data => {
                if (data.logged) {
                    navigate('/account');
                } else {
                    toast.error(data.error);
                }
            })
            .catch(error => toast.error(error))
    }

    function onLogin(data) {
        //setting user session
        localStorage.setItem('data', JSON.stringify({token: data.token}));
        //redirecting user to the account page
        navigate('/account')
    }

    return (
        <>
            <Header/>
            <div className="nav-tabs">
                <a className="nav-link active">Login</a>
            </div>
            <form className="login-form" onSubmit={onSubmit}>
                <input ref={email} type="email" name="email" placeholder="Email" required/>
                <input ref={password} type="password" name="password" placeholder="password" required/>
                <button type="submit">Log In</button>
                <OwnID type='login'
                       passwordField={password}
                       loginIdField={email}
                       onError={(error) => console.error(error)}
                       onLogin={onLogin}/>
            </form>
            <div className="custom-link" onClick={() => navigate('/register')}>
                <div className="link-text">Don't have an account?</div>
            </div>
        </>
    );
}

export default LoginForm;

// Frontend/Custom/Angular/src/app/components/login-form/login-form.component.ts
import { Component, OnInit } from '@angular/core';
import {WidgetType} from "@ownid/angular";
import {HttpRequestService} from "../../services/http-request.service";
import {Router} from "@angular/router";
import {FormBuilder, FormGroup, Validators} from "@angular/forms";

@Component({
  selector: 'app-login-form',
  templateUrl: './login-form.component.html',
  styleUrls: ['./login-form.component.scss']
})
export class LoginFormComponent implements OnInit {

  login: WidgetType = WidgetType.Login;
  loginIdField: string | undefined;
  passwordField: string | undefined;
  userForm: FormGroup;

  constructor(private httpService: HttpRequestService, private router: Router,formBuilder: FormBuilder) {
    this.userForm = formBuilder.group(
      {
        email: [null, [Validators.required]],
        password: [null, [Validators.required]],
      },
      {updateOn: 'change'});
  }


  ngOnInit(): void {
  }

  onLogin() {
    this.router.navigateByUrl('/account');
  }

  onSubmit() {
    this.httpService.signInUser(this.userForm.get('email')?.value, this.userForm.get('password')?.value)
      .subscribe({
        next: (data) => {
          if(data.logged) {
            this.onLogin()
          } else {
            alert(data.error);
          }
        },
        error: (err) => console.error(err),
      })
  }
}

<div class="nav-tabs">
  <a class="nav-link active">Login</a>
</div>
<form [formGroup]="userForm" class="login-form" (ngSubmit)="onSubmit()">
  <input formControlName="email"  type="email" #email name="email" placeholder="Email" required/>
  <input formControlName="password" type="password" #password name="password" placeholder="password" required/>
  <button type="submit">Log In</button>
  <ownid [type]="login"
         [options] = widgetOptions
         (onLogin)="onLogin()"
         [loginIdField]="email"
         [passwordField]="password">
  </ownid>
</form>
<div class="custom-link">
<div class="link-text" routerLink="/register">Don't have an account?</div>
</div>
