// Frontend/Custom/ReactJS/src/components/RegisterForm/RegisterForm.jsx
import React, {useRef, useState} from "react";
import './registerForm.scss';
import 'react-toastify/dist/ReactToastify.css';
import {OwnID} from "@ownid/react";
import {useNavigate} from "react-router-dom";
import Header from "../Header/Header";
import {httpPostRequest, loginUser, registerUser} from "../../services/httpRequests";
import {toast} from "react-toastify";

function RegisterComponent() {
    const emailField = useRef(null);
    const passwordField = useRef(null);
    const [ownIDData, setOwnIDData] = useState(null);
    let navigate = useNavigate();

    // Stores ownIdData
    function onRegister(ownIdData) {
        setOwnIDData(ownIdData);
    }

    function onSubmit(event,userData1) {
        event.preventDefault();
        //Call your existing registration logic in the backend
        const userData = {loginId: emailField.current.value, password: passwordField.current.value};
        return register({...userData, ...{ownIdData: ownIDData}});
    }

    function register(userData) {

        registerUser(userData)
            .then(data => {
                if (data.created) {
                    navigate('/login')
                } else {
                    toast.error(data.error);
                }
            })
            .catch(error => toast.error(error))
    }

    return (
        <>
            <Header/>
            <div className="nav-tabs">
                <a className="nav-link active">Register</a>
            </div>
            <form onSubmit={onSubmit} className="login-form">
                <input ref={emailField} type="email" name="email" placeholder="Email" required/>
                <input ref={passwordField} type="password" name="password" placeholder="password" required/>
                <button type="submit">Register</button>
                <OwnID type='register'
                       options={{ variant: 'button-fingerprint', infoTooltip:true }}
                       loginIdField={emailField}
                       passwordField={passwordField}
                       onError={(error) => console.error(error)}
                       onRegister={onRegister}/>
            </form>
            <div className="custom-link" onClick={() => navigate('/login')}>
                <div className="link-text">Already have an account?</div>
            </div>
        </>
    );
}

export default RegisterComponent;

// Frontend/Custom/Angular/src/app/components/register-form/register-form.component.ts
import { Component, OnInit } from '@angular/core';
import {HttpRequestService} from "../../services/http-request.service";
import {Router} from "@angular/router";
import {InlineWidgetVariants, WidgetType} from "@ownid/angular";
import {FormBuilder, FormGroup, Validators} from "@angular/forms";

@Component({
  selector: 'app-register-form',
  templateUrl: './register-form.component.html',
  styleUrls: ['./register-form.component.scss']
})
export class RegisterFormComponent implements OnInit {

  widgetOptions = { variant: InlineWidgetVariants.ButtonFingerprint, infoTooltip: true };
  register: WidgetType = WidgetType.Register;
  loginIdField: string | undefined;
  passwordField: string | undefined;
  ownIDData: string | undefined;
  userForm: FormGroup;

  constructor(private httpService: HttpRequestService, private router: Router,formBuilder: FormBuilder) {
    this.userForm = formBuilder.group(
      {
        email: [null, [Validators.required]],
        password: [null, [Validators.required]],
      },
      {updateOn: 'change'});
  }

  ngOnInit(): void {
  }

  onRegister(ownIdData: string) {
    this.ownIDData = ownIdData;
  }

  onSubmit() {
    this.httpService.registerUser(this.userForm.get('email')?.value, this.userForm.get('password')?.value
      ,this.ownIDData || '')
      .subscribe({
        next: (data) => {
          if(data.created) {
            this.router.navigateByUrl('/login')
          } else {
            alert(data.error);
          }
        },
        error: (err) => console.error(err),
      })
  }
}

<div class="nav-tabs">
  <a class="nav-link active">Register</a>
</div>
<form [formGroup]="userForm" class="registration-form" (ngSubmit)="onSubmit()">
  <input formControlName="email"  type="email" #email name="email" placeholder="Email" required/>
  <input formControlName="password" type="password" #password name="password" placeholder="password" required/>
  <button type="submit">Register</button>
  <ownid [type]="register"
         [options] = widgetOptions
         (onRegister)="onRegister($event)"
         [loginIdField]="email"
         [passwordField]="password">
  </ownid>
</form>
<div class="custom-link">
<div class="link-text" routerLink="/login">Already have an account?</div>
</div>
